---
---
title: "36-315 Homework 09, Spring 2018"
author: "Jenny Zhang yijiaz2, Chuning Yang chuningy,Xiang Si xsi"
date: "Due Wednesday, April 4, 2018 (11:59pm) on Canvas"
output: 
  html_document:
    toc:  true
    toc_float:  true
    code_folding:  show
---

#  Poster
---

```{r}
library(tidyverse)
```
```{r}
uni_data <- read.csv("universities.csv")

data_colnames <- c("rank","sat_avg", "acceptance_rate", "state",
                   "tuition", "overallRank", "institutionalControl",
                   "percent_receiving_aid", "percent_receiving_aid",
                   "cost_after_aid", "hs_gpa_avg",
                   "tuition", "engineeringRepScore")

uni_data <- uni_data[data_colnames]

```


Graph for tutition vs ranking(denogram?)
```{r}


```

Graph for institutioal Control of the first 150 ranking universities
```{r}
instiControl_data <- uni_data[c(1:150),c(1:7)]

ggplot(instiControl_data, aes(x = rank, color = institutionalControl)) + 
  geom_density(adjust = .7, size = 1) + 
  labs(x = "Ranking",
       y = "Density",
       color = "Institutional Control",
       title = "Distribution of Private vs Public School in 
       Universities Ranked First 150",
       caption = "Source:https://www.kaggle.com/theriley106/university-statistics")
```


```{r}
us_data <- map_data("state")
state_borders <- map_data("state")
library(datasets)
college_count_by_state <- instiControl_data %>% 
  group_by(state) %>%
  summarize(college_num = n())

college_count_by_state$state <- state.name[match(college_count_by_state$state, state.abb)]
college_count_by_state <- college_count_by_state %>%
  mutate(state=tolower(state))
state_borders <- state_borders %>%
  left_join(college_count_by_state, 
            by = c("region" = "state"))

ggplot(state_borders) + 
  geom_polygon(aes(x = long, y = lat, group = group,
                   fill = college_num), color = "black") + 
  scale_fill_gradient2(low = "blue", mid = "white", 
                         high = "darkred", midpoint = 4) +
  theme_void() +
  coord_map("polyconic") + 
  labs(
    title = "Top 150 Universities in the U.S. by State",
    caption = "Source: https://www.kaggle.com/theriley106/university-statistics",
    fill = "# of Top 150 Universities"
  ) + 
  theme(legend.position = "bottom")

```

```{r}
ggplot(uni_data, aes(x = sat_avg, y=engineeringRepScore, color=institutionalControl))+
  geom_point()+
  labs(title = "Distribution of Engineering Reputation Score and student SAT average",
       x = "SAT Average",
       y = "Engineering Reputation Score",
       caption = "Source: https://www.kaggle.com/theriley106/university-statistics")
```

```{r}
library(ggplot2)
#plot1
ggplot(uni_data, aes(x = sat_avg, y = acceptance_rate, colour = uni_data$institutionalControl)) +
  geom_jitter() +
  labs(x = "SAT Average", y = "Acceptance Rate", colour = "Institutional Type",
       title = "Distribution of SAT score by Acceptance Rate") 
#plot2
ggplot(uni_data, aes(x = tuition)) +
  geom_histogram(bins = 25) + 
  geom_rug() + 
  labs(x = "Tuition", y = "Count",
       title = "Distribution of Tuiton among U.S colleges")

#plot3
ggplot(data = uni_data, aes(x = sat_avg, fill = institutionalControl)) +
  geom_histogram(bins = 10)  +
  labs(title = "Proportional stacked bar chart of insitutional type by SAT distribution",
       x = "SAT average", 
       y = "Count",
       fill = "Institutional Type") + 
  theme(legend.position = "bottom")
```



```{r}
state_borders <- map_data("state")
library(datasets)
college_count_by_state <- uni_data %>% 
  group_by(state) %>%
  summarize(avg_tuition = mean(tuition, na.rm = TRUE))

college_count_by_state$state <- state.name[match(college_count_by_state$state, state.abb)]
college_count_by_state <- college_count_by_state %>%
  mutate(state=tolower(state))
state_borders <- state_borders %>%
  left_join(college_count_by_state, 
            by = c("region" = "state"))

ggplot(state_borders) + 
  geom_polygon(aes(x = long, y = lat, group = group,
                   fill = avg_tuition), color = "black") + 
  scale_fill_gradient2(low = "yellow", mid = "white", 
                         high = "purple", midpoint = 25000) +
  theme_void() +
  coord_map("polyconic") + 
  labs(
    title = "Average Tuition Of Colleges the U.S. by State",
    caption = "Source: https://www.kaggle.com/theriley106/university-statistics",
    fill = "Avg Tuitions"
  ) + 
  theme(legend.position = "bottom")
```







